Repository Tavern-Keeper-2308/tavern-keeper-fe, pull requests merged in 2024-02, with the labels that each got.

#5 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#6 Update README.md
  README.md
  docs/README.md
  docs/pull_request_template.md
Labels: documentation

#16 Feature/modular file structure
  docs/README.md
  public/logo192.png
  public/logo512.png
  public/manifest.json
  pull_request_template.md
  src/App.js
  src/apiCalls.js
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/App/App.test.js
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Header.test.js
  src/index.js
  src/logo.svg
Labels: documentation

#36 Feature/page title and favicon
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/safari-pinned-tab.svg
Labels: task

#38 Setup/component architecture+imports
  package-lock.json
  package.json
  src/components/App/App.jsx
  src/components/EncounterBuilder/EncounterBuilder.css
  src/components/EncounterBuilder/EncounterBuilder.jsx
  src/components/EncounterBuilderButton/EncounterBuilderButton.css
  src/components/EncounterBuilderButton/EncounterBuilderButton.jsx
  src/components/EncounterDetails/EncounterDetails.css
  src/components/EncounterDetails/EncounterDetails.jsx
  src/components/EncounterPreviewCard/EncounterPreviewCard.css
  src/components/EncounterPreviewCard/EncounterPreviewCard.jsx
  src/components/EncounterPreviewContainer/EncounterPreviewContainer.css
  src/components/EncounterPreviewContainer/EncounterPreviewContainer.jsx
  src/components/Home/Home.css
  src/components/Home/Home.jsx
  src/components/Login/Login.css
  src/components/Login/Login.jsx
  src/components/LogoutButton/LogoutButton.css
  src/components/LogoutButton/LogoutButton.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
  src/components/Navigation/Navigation.test.js
  src/mockData.js
Labels: task

#44 Feature/navigation
  public/index.html
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/EncounterBuilder/EncounterBuilder.jsx
  src/components/EncounterBuilderButton/EncounterBuilderButton.jsx
  src/components/Login/Login.jsx
  src/components/LogoutButton/LogoutButton.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
Labels: task

#48 Feature/preview page
  src/components/App/App.jsx
  src/components/EncounterPreviewCard/EncounterPreviewCard.css
  src/components/EncounterPreviewCard/EncounterPreviewCard.jsx
  src/components/EncounterPreviewContainer/EncounterPreviewContainer.css
  src/components/EncounterPreviewContainer/EncounterPreviewContainer.jsx
  src/components/Home/Home.css
  src/components/Home/Home.jsx
  src/mockData.js
  src/mockDataset.js
Labels: user story

#51 Feature/3 button login page
  src/components/App/App.css
  src/components/EncounterPreviewCard/EncounterPreviewCard.css
  src/components/Login/Login.css
  src/components/Login/Login.jsx
  src/components/Navigation/Navigation.css
Labels: user story

#45 feat/details page contents
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/EncounterDetails/EncounterDetails.css
  src/components/EncounterDetails/EncounterDetails.jsx
  src/components/EncounterPreviewCard/EncounterPreviewCard.jsx
  src/mockDataset.js
Labels: task, user story

#56 Fix/universalize background
  src/components/EncounterDetails/EncounterDetails.css
  src/components/EncounterDetails/EncounterDetails.jsx
  src/components/ErrorPage/ErrorPage.css
  src/components/Home/Home.css
  src/components/Login/Login.css
Labels: bug

#57 Feature/connect login buttons with apollo graphql
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/EncounterPreviewCard/EncounterPreviewCard.jsx
  src/components/Home/Home.jsx
  src/components/Login/Login.jsx
  src/components/LogoutButton/LogoutButton.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
Labels: task

#65 fix: Get rid of error on logout
  src/components/App/App.css
  src/components/App/App.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
Labels: bug

#66 Feature/use api for encounter details
  src/components/App/App.jsx
  src/components/EncounterDetails/EncounterDetails.css
  src/components/EncounterDetails/EncounterDetails.jsx
  src/components/EncounterPreviewCard/EncounterPreviewCard.css
  src/components/EncounterPreviewCard/EncounterPreviewCard.jsx
  src/components/EncounterPreviewContainer/EncounterPreviewContainer.jsx
  src/components/Home/Home.jsx
Labels: task

#68 Test/install and implement cypress
  cypress.config.js
  cypress/e2e/errorhandling_spec.cy.js
  cypress/e2e/functional_spec.cy.js
  cypress/fixtures/mock_data_createEncounter.json
  cypress/fixtures/mock_data_getEncounter.json
  cypress/fixtures/mock_data_getEncounters.json
  cypress/fixtures/mock_data_getMonster.json
  cypress/fixtures/mock_data_getMonsters.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: test

#67 Add Deployment to README
  docs/README.md
Labels: documentation

#71 docs/README
  docs/README.md
Labels: documentation

#69 Test/functional cypress tests
  cypress/e2e/functional_spec.cy.js
  cypress/fixtures/mock_data_createEncounter.json
  cypress/fixtures/mock_data_getEncounter.json
  cypress/fixtures/mock_data_getEncounters_many.json
  cypress/fixtures/mock_data_getEncounters_new_data.json
  cypress/fixtures/mock_data_getEncounters_none.json
  cypress/fixtures/mock_data_getEncounters_one.json
  cypress/fixtures/mock_data_getMonster_ancient_red_dragon.json
  cypress/fixtures/mock_data_getMonster_kobold.json
  cypress/fixtures/mock_data_getMonsters.json
  cypress/utils/graphql-test-utils.js
  src/components/EncounterBuilder/EncounterBuilder.jsx
  src/components/EncounterBuilderButton/EncounterBuilderButton.jsx
  src/components/EncounterDetails/EncounterDetails.jsx
  src/components/LogoutButton/LogoutButton.jsx
  src/components/MonsterFilter/MonsterFilter.jsx
Labels: test
